### PR TITLE
Add new projects

### PR DESCRIPTION
**Pull request by monsij**
Fresh projects for GSoC Heat '19 added

### CODE REVIEW

**Comment by pandusonu2** [comment]
Remove projects which are not applicable for this yr's GSoC Heat

**Comment by monsij** [comment]
Done :-) @pandusonu2

**Comment by pandusonu2** [comment]
Commit message format: https://nitdgpos.github.io/get_involved

**Comment by naveenkumarsangi** [comment]
@monsij Amend your commit message, please.

**Comment by monsij** [comment]
Sure. Ill do it tonight!

**Comment by monsij** [comment]
@pandusonu2  @nkprince007 Shall I open a new PR from a new branch, rest all changes have been made. I'll keep that in mind surely from next time. 😄

**Comment by pandusonu2** [comment]
Just force push na, PR will get updated

**Comment by monsij** [comment]
:3 Let's google how to do it...haven't done it yet

**Comment by pandusonu2** [comment]
Didn't you just do that few minutes ago 😅

I didn't check the commit/changes that but PR says you force pushed (/.\)

Just lemme know if it's the final wala

**Comment by monsij** [comment]
But I want to change branch from `master` to `<a new branch>`. Is it possible too ? I haven't followed this:
mistake

**Comment by monsij** [comment]
Ending all confusions,PR migrated to #39

**Pull request closed without merging**
